# Generated by Django 4.2 on 2023-05-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensor",
            name="time_interval",
            field=models.FloatField(),
        ),
    ]
